# Generated by Django 5.1 on 2024-09-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('X', 'Cancelada')], default='P', max_length=1),
        ),
    ]
