# Generated by Django 5.1 on 2024-09-04 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='state',
        ),
    ]
